name: password
version: 3.0.0
description: A set of high-level APIs over PointyCastle to hash and verify passwords securely.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/password-dart
environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  pointycastle: ^4.0.0

dev_dependencies:
  test: ^1.31.1
